# Generated by Django 3.2.9 on 2021-11-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=50)),
                ('kilometraje', models.IntegerField()),
            ],
        ),
    ]
